<?php
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;
/**
 * Implements hook_mail().
 */
function myform_mail($key, &$message, $params) {
    $options = array(
        'langcode' => $message['langcode'],
    );
    switch ($key) {
        case 'node_insert':
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = t('Your mail subject Here: @title', array('@title' => $params['title']), $options);
            $message['body'][] = Html::escape($params['message']);
            break;
    }
}